/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.45
 * Generated at: 2017-07-14 20:09:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/views/header.jsp", Long.valueOf(1500062616451L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://www.w3schools.com/w3css/4/w3.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Raleway\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-inverse\">\r\n");
      out.write("  <div class=\"container-fluid\">\r\n");
      out.write("    <div class=\"navbar-header\">\r\n");
      out.write("      <a class=\"navbar-brand\" href=\"#\"> UNIVERSE\r\n");
      out.write("        </a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <ul class=\"nav navbar-nav\">\r\n");
      out.write("      <li class=\"active\"><a href=\"http://localhost:8080/Book/home\">\r\n");
      out.write("          <span class=\"glyphicon glyphicon-home\"></span> \r\n");
      out.write("        </a></li>\r\n");
      out.write("<li class=\"dropdown\">\r\n");
      out.write("          <a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\">CATEGIRIES\r\n");
      out.write("          <span class=\"caret\"></span></a>\r\n");
      out.write("          <ul class=\"dropdown-menu\">\r\n");
      out.write("            <li><a href=\"#\">BIKE1</a></li>\r\n");
      out.write("            <li><a href=\"#\">BIKE</a></li>\r\n");
      out.write("            <li><a href=\"#\">BIKE 3</a></li> \r\n");
      out.write("          </ul>\r\n");
      out.write("        </li><li><a href=\"http://localhost:8080/Book/aboutus\">ABOUT US</a></li>\r\n");
      out.write("        <li><a href=\"http://localhost:8080/Book/getproductform\">ADD PRODUCT</a></li>\r\n");
      out.write("             <li><a href=\"http://localhost:8080/Book//all/product/getallproducts\">PRODUCT LIST</a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>BIKES</title>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://www.w3schools.com/w3css/4/w3.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Raleway\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("<style>\r\n");
      out.write("body,h1,h2,h3,h4,h5,h6 {font-family: \"Raleway\", Arial, Helvetica, sans-serif}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<body style=\"background-color:powderblue;\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Navigation Bar -->\r\n");
      out.write("<div class=\"w3-bar w3-white w3-large\">\r\n");
      out.write("  <a href=\"#\" class=\"w3-bar-item w3-button w3-red w3-mobile\"><i class=\"fa fa-globe w3-margin-right\"></i>UNIVERSE</a>\r\n");
      out.write("   <a  class=\"w3-bar-item w3-button w3-mobile\">BIKES</a>\r\n");
      out.write("  <a href=\"#contact\" class=\"w3-bar-item w3-button w3-mobile\">Contact</a>\r\n");
      out.write("   <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("        <li><a href=\"#\"><span class=\"glyphicon glyphicon-user\"></span> Sign Up</a></li>\r\n");
      out.write("        <li><a href=\"#\"><span class=\"glyphicon glyphicon-log-in\"></span> Login</a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("  <h2>BIKES TRENDING NOW</h2>  \r\n");
      out.write("  <div id=\"myCarousel\" class=\"carousel slide\" data-ride=\"carousel\">\r\n");
      out.write("    <!-- Indicators -->\r\n");
      out.write("    <ol class=\"carousel-indicators\">\r\n");
      out.write("      <li data-target=\"#myCarousel\" data-slide-to=\"0\" class=\"active\"></li>\r\n");
      out.write("      <li data-target=\"#myCarousel\" data-slide-to=\"1\"></li>\r\n");
      out.write("      <li data-target=\"#myCarousel\" data-slide-to=\"2\"></li>\r\n");
      out.write("    </ol>\r\n");
      out.write("\r\n");
      out.write("    <!-- Wrapper for slides -->\r\n");
      out.write("    <div class=\"carousel-inner\">\r\n");
      out.write("      <div class=\"item active\">\r\n");
      out.write("        <img src=\"resources/images/ravi7.jpg\" alt=\"ravi7\" style=\"width:100%;\">\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"item\">\r\n");
      out.write("        <img src=\"resources/images/ravi6.jpg\" alt=\"ravi6\" style=\"width:100%;\">\r\n");
      out.write("      </div>\r\n");
      out.write("    \r\n");
      out.write("      <div class=\"item\">\r\n");
      out.write("        <img src=\"resources/images/ravi6.jpg\" alt=\"ravi6\" style=\"width:100%;\">\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Left and right controls -->\r\n");
      out.write("    <a class=\"left carousel-control\" href=\"#myCarousel\" data-slide=\"prev\">\r\n");
      out.write("      <span class=\"glyphicon glyphicon-chevron-left\"></span>\r\n");
      out.write("      <span class=\"sr-only\">Previous</span>\r\n");
      out.write("    </a>\r\n");
      out.write("    <a class=\"right carousel-control\" href=\"#myCarousel\" data-slide=\"next\">\r\n");
      out.write("      <span class=\"glyphicon glyphicon-chevron-right\"></span>\r\n");
      out.write("      <span class=\"sr-only\">Next</span>\r\n");
      out.write("    </a>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Page content -->\r\n");
      out.write("<div class=\"w3-content\" style=\"max-width:1532px;\">\r\n");
      out.write("\r\n");
      out.write("  <div class=\"w3-container w3-margin-top\" id=\"rooms\">\r\n");
      out.write("    <h3>BIKES</h3>\r\n");
      out.write("    <p> We offer the best bikes. ride well and live well.</p>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("  <div class=\"w3-row-padding\">\r\n");
      out.write("    <div class=\"w3-col m3\">\r\n");
      out.write("      <label><i class=\"fa fa-currency\"></i> Price from</label>\r\n");
      out.write("      <input class=\"w3-input w3-border\" type=\"number\" >\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"w3-col m3\">\r\n");
      out.write("      <label><i class=\"fa fa-currency\"></i> Check Out</label>\r\n");
      out.write("      <input class=\"w3-input w3-border\" type=\"number\" >\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"w3-col m2\">\r\n");
      out.write("      <label><i class=\"fa fa-bike\"></i> BIKE</label>\r\n");
      out.write("      <input class=\"w3-input w3-border\" type=\"number\" placeholder=\"1\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"w3-col m2\">\r\n");
      out.write("      <label><i class=\"fa fa-child\"></i> COLOR</label>\r\n");
      out.write("      <input class=\"w3-input w3-border\" type=\"number\" placeholder=\"0\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"w3-col m2\">\r\n");
      out.write("      <label><i class=\"fa fa-search\"></i> Search</label>\r\n");
      out.write("      <button class=\"w3-button w3-block w3-black\">Search</button>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"w3-row-padding w3-padding-16\">\r\n");
      out.write("    <div class=\"w3-third w3-margin-bottom\">\r\n");
      out.write("      <img src=\"resources/images/ravi6.jpg\" alt=\"ravi6\" style=\"width:100%\">\r\n");
      out.write("      <div class=\"w3-container w3-white\">\r\n");
      out.write("        <h3>DUKE</h3>\r\n");
      out.write("        <h6 class=\"w3-opacity\">From $999999</h6>\r\n");
      out.write("        <p>simply superb</P>\r\n");
      out.write("\r\n");
      out.write("        <button class=\"w3-button w3-block w3-black w3-margin-bottom\">BOOK</button>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"w3-third w3-margin-bottom\">\r\n");
      out.write("      <img src=\"resources/images/ravi7.jpg\" alt=\"ravi7\" style=\"width:100%\">\r\n");
      out.write("      <div class=\"w3-container w3-white\">\r\n");
      out.write("        <h3>APACHI</h3>\r\n");
      out.write("        <h6 class=\"w3-opacity\">From $111449</h6>\r\n");
      out.write("        <p>now present trend</p>\r\n");
      out.write("       \r\n");
      out.write("       \r\n");
      out.write("        <button class=\"w3-button w3-block w3-black w3-margin-bottom\">book</button>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"w3-third w3-margin-bottom\">\r\n");
      out.write("      <img src=\"resources/images/ravi1.JPG\" alt=\"ravi1\" style=\"width:100%\">\r\n");
      out.write("      <div class=\"w3-container w3-white\">\r\n");
      out.write("        <h3>KARISHMA</h3>\r\n");
      out.write("        <h6 class=\"w3-opacity\">From $199</h6>\r\n");
      out.write("        <p>classy touch</p>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        <button class=\"w3-button w3-block w3-black w3-margin-bottom\">BOOK</button>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"w3-row-padding\" id=\"about\">\r\n");
      out.write("    <div class=\"w3-col l4 m7\">\r\n");
      out.write("      <h3>About</h3>\r\n");
      out.write("      <h6>Our Bikes is one of a kind. It is truely amazing.First of all about my bikes,give good mailage.we can do the  </h6>\r\n");
      out.write("    <p>We accept: <i class=\"fa fa-credit-card w3-large\"></i> <i class=\"fa fa-cc-mastercard w3-large\"></i> <i class=\"fa fa-cc-amex w3-large\"></i> <i class=\"fa fa-cc-cc-visa w3-large\"></i><i class=\"fa fa-cc-paypal w3-large\"></i></p>\r\n");
      out.write("    </div>\r\n");
      out.write("   \r\n");
      out.write("  \r\n");
      out.write("  <div class=\"w3-row w3-large w3-center\" style=\"margin:32px 0\">\r\n");
      out.write("    <div class=\"w3-third\"><i class=\"fa fa-map-marker w3-text-red\"></i> 423 Some adr, chennai</div>\r\n");
      out.write("    <div class=\"w3-third\"><i class=\"fa fa-phone w3-text-red\"></i> Phone: +91 9963151515</div>\r\n");
      out.write("    <div class=\"w3-third\"><i class=\"fa fa-envelope w3-text-red\"></i> Email: ravirkr96@mail.com</div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"w3-panel w3-red w3-leftbar w3-padding-32\">\r\n");
      out.write("    <h6><i class=\"fa fa-info w3-deep-orange w3-padding w3-margin-right\"></i> On demand, we can offer helmet, sport dress, glasses etc.</h6>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"w3-container\">\r\n");
      out.write("    <h3>Our BIKES</h3>\r\n");
      out.write("    <h6>You can find my showrooms in some places</h6>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("  <div class=\"w3-row-padding w3-padding-16 w3-text-white w3-large\">\r\n");
      out.write("    <div class=\"w3-half w3-margin-bottom\">\r\n");
      out.write("      <div class=\"w3-display-container\">\r\n");
      out.write("        <img src=\"resources/images/ravi11.jpg\" alt=\"ravi11\" style=\"width:100%\">\r\n");
      out.write("        <span class=\"w3-display-bottomleft w3-padding\">AMARAVATHI</span>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"w3-half\">\r\n");
      out.write("      <div class=\"w3-row-padding\" style=\"margin:0 -16px\">\r\n");
      out.write("        <div class=\"w3-half w3-margin-bottom\">\r\n");
      out.write("          <div class=\"w3-display-container\">\r\n");
      out.write("            <img src=\"resources/images/ravi10.jpg\" alt=\"ravi10\" style=\"width:100%\">\r\n");
      out.write("            <span class=\"w3-display-bottomleft w3-padding\">MUMBAI</span>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"w3-half w3-margin-bottom\">\r\n");
      out.write("          <div class=\"w3-display-container\">\r\n");
      out.write("            <img src=\"resources/images/ravi10.jpg\" alt=\"ravi10\" style=\"width:100%\">\r\n");
      out.write("            <span class=\"w3-display-bottomleft w3-padding\">DELHI</span>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"w3-row-padding\" style=\"margin:0 -16px\">\r\n");
      out.write("        <div class=\"w3-half w3-margin-bottom\">\r\n");
      out.write("          <div class=\"w3-display-container\">\r\n");
      out.write("            <img src=\"resources/images/ravi12.jpg\" alt=\"ravi12\" style=\"width:100%\">\r\n");
      out.write("            <span class=\"w3-display-bottomleft w3-padding\">SECUDRABAD</span>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"w3-half w3-margin-bottom\">\r\n");
      out.write("          <div class=\"w3-display-container\">\r\n");
      out.write("            <img src=\"resources/images/ravi11.jpg\" alt=\"ravi11\" style=\"width:100%\">\r\n");
      out.write("            <span class=\"w3-display-bottomleft w3-padding\">KURNOOL</span>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"w3-container w3-padding-32 w3-black w3-opacity w3-card-2 w3-hover-opacity-off\" style=\"margin:32px 0;\">\r\n");
      out.write("    <h2>Get the best offers first!</h2>\r\n");
      out.write("    <p>Join our newsletter.</p>\r\n");
      out.write("    <label>E-mail</label>\r\n");
      out.write("    <input class=\"w3-input w3-border\" type=\"text\" placeholder=\"Your Email address\">\r\n");
      out.write("    <button type=\"button\" class=\"w3-button w3-red w3-margin-top\">Subscribe</button>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"w3-container\" id=\"contact\">\r\n");
      out.write("    <h2>Contact</h2>\r\n");
      out.write("    <p>If you have any questions, do not hesitate to ask them.</p>\r\n");
      out.write("    <i class=\"fa fa-map-marker w3-text-red\" style=\"width:30px\"></i> chennai , India<br>\r\n");
      out.write("    <i class=\"fa fa-phone w3-text-red\" style=\"width:30px\"></i> Phone: +91 9666665515<br>\r\n");
      out.write("    <i class=\"fa fa-envelope w3-text-red\" style=\"width:30px\"> </i> Email: universebikes96@mail.com<br>\r\n");
      out.write("    <form action=\"/action_page.php\" target=\"_blank\">\r\n");
      out.write("      <p><input class=\"w3-input w3-padding-16 w3-border\" type=\"text\" placeholder=\"Name\" required name=\"Name\"></p>\r\n");
      out.write("      <p><input class=\"w3-input w3-padding-16 w3-border\" type=\"text\" placeholder=\"Email\" required name=\"Email\"></p>\r\n");
      out.write("      <p><input class=\"w3-input w3-padding-16 w3-border\" type=\"text\" placeholder=\"Message\" required name=\"Message\"></p>\r\n");
      out.write("      <p><button class=\"w3-button w3-black w3-padding-large\" type=\"submit\">SEND MESSAGE</button></p>\r\n");
      out.write("    </form>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("<!-- End page content -->\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Footer -->\r\n");
      out.write("<footer class=\"w3-padding-32 w3-black w3-center w3-margin-top\">\r\n");
      out.write("  <h5>Find Us On</h5>\r\n");
      out.write("  <div class=\"w3-xlarge w3-padding-16\">\r\n");
      out.write("    <i class=\"fa fa-facebook-official w3-hover-opacity\"></i>\r\n");
      out.write("    <i class=\"fa fa-instagram w3-hover-opacity\"></i>\r\n");
      out.write("    <i class=\"fa fa-snapchat w3-hover-opacity\"></i>\r\n");
      out.write("    <i class=\"fa fa-pinterest-p w3-hover-opacity\"></i>\r\n");
      out.write("    <i class=\"fa fa-twitter w3-hover-opacity\"></i>\r\n");
      out.write("    <i class=\"fa fa-linkedin w3-hover-opacity\"></i>\r\n");
      out.write("  </div>\r\n");
      out.write("  <p>Powered by <a href=\"https://www.UNIVERSE bikes.com/w3css/default.asp\" target=\"_blank\" class=\"w3-hover-text-green\"> UNIVERSE Bikes</a></p>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("  \r\n");
      out.write(" ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
